version: "3.8"

# base configuration
services:
  db:
    image: postgres:13.4
    container_name: csdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=csdb
      - POSTGRES_USER=csroot
      - POSTGRES_PASSWORD=cspass

  web:
    image: cs-platform-web
    build: ./server
    command: poetry run src/manage.py runserver 0.0.0.0:8000
    container_name: csweb
    volumes:
      - ./server/src:/code/src
      - ./server/pyproject.toml:/code/pyproject.toml
      - ./server/poetry.lock:/code/poetry.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
