version: "3.8"

# base configuration
services:
  db:
    environment:
      - POSTGRES_DB=csdb
      - POSTGRES_USER=csroot
      - POSTGRES_PASSWORD=cspass

  api:
    image: cs-platform-api:prod
    command: poetry run src/manage.py runserver 0.0.0.0:8000

  app:
    image: cs-platform-app:prod
    build:
      target: prod
    ports:
      - "80:80"
    depends_on:
      - api
