version: "3.8"

services:
  db:
    image: postgres:13.4
    container_name: csdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=csdb
      - POSTGRES_USER=csroot
      - POSTGRES_PASSWORD=cspass

  web:
    image: cs-platform-web
    build: .
    command: poetry run server/manage.py runserver 0.0.0.0:8000
    container_name: csweb
    volumes:
      - ./server:/code/server
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
