version: "3.8"

# base configuration for local development
services:
  db:
    image: postgres:13.4
    container_name: csdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=csdb
      - POSTGRES_USER=csroot
      - POSTGRES_PASSWORD=cspass

  api:
    image: cs-platform-api
    build: ./api
    # run poetry install once more to install dev-dependencies
    command: bash -c "poetry install && poetry run src/manage.py runserver 0.0.0.0:8000"
    container_name: csapi
    volumes:
      - ./api/src:/code/src
      - ./api/pyproject.toml:/code/pyproject.toml
      - ./api/poetry.lock:/code/poetry.lock
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # required by pytest-django to find manage.py
      - PYTHONPATH=src
